### PR TITLE
rpm: fold WAL/SHM cleanup into sqlite close closure

### LINKED ISSUE #1844: SQLite WAL/SHM spool side-files leak in os.TempDir() after RPM scan
## Summary

When `claircore`'s RPM scanner runs against an SQLite-backend RPM database
(Rocky 9 / RHEL 9 / Fedora 35+), it leaves orphaned `*-wal` and `*-shm` files
in `os.TempDir()` after every scan, e.g.:

```text
$ ls /tmp | grep rpm
rpm.package.sqlite.4257389849-shm
rpm.package.sqlite.4257389849-wal
```

The main spool file (`rpm.package.sqlite.4257389849`) is correctly unlinked,
but its SQLite companion files survive. They accumulate over the lifetime of
any long-running process (e.g. an agent that scans on a schedule).

This does **not** reproduce on CentOS 6/7 because those distros use the BDB
backend, which is parsed in-memory without opening a real SQLite connection.

## Root cause

In `internal/rpm/find.go`:

```go
func (c *databaseCleanup) Close() (err error) {
    if c.spool != nil {
        err = errors.Join(err, c.spool.Close(), os.Remove(c.spool.Name())) // (1) main file unlinked
    }
    if c.close != nil {
        err = errors.Join(err, c.close())                                  // (2) sqlite.Close runs *after*
    }
    return err
}
```

Two things go wrong, in order:

1. The main spool file is unlinked **before** `sdb.Close()` is invoked. By the
   time the SQLite driver (`modernc.org/sqlite`) gets a chance to perform its
   clean shutdown — which is what removes WAL/SHM — the main DB file has
   already been unlinked. SQLite's shutdown sequence assumes the main file is
   still present; some platform/filesystem combinations result in the side
   files being abandoned.
2. Even if SQLite did manage to unlink the WAL/SHM during shutdown, this
   ordering is fragile: SQLite's WAL checkpoint / shutdown semantics are
   documented around the main file existing on disk.

`Open` in `internal/rpm/sqlite/sqlite.go` opens the connection with
`_pragma=query_only(1)`, which makes the connection read-only at the SQL level,
but the driver still creates `-wal` / `-shm` companions on the filesystem.

### PR DESCRIPTION
**Pull request by crozzy**
Add SQLite-specific teardown inside the kindSQLite branch via a closure.

### CODE REVIEW

**Comment by crozzy** [comment]
Based on https://github.com/quay/claircore/pull/1845 (a community PR)

**Comment by crozzy** [comment]
fixes https://github.com/quay/claircore/issues/1844

File: internal/rpm/find.go [hunk 1]
```diff
@@ -226,7 +226,19 @@ func OpenDB(ctx context.Context, sys fs.FS, found FoundDB) (*Database, error) {
 			return nil, fmt.Errorf("internal/rpm: unable to open sqlite db: %w", err)
 		}
 		db.headers = sdb
-		cleanup.close = sdb.Close
+		spoolPath := spool.Name()
+		cleanup.close = func() error {
+			var err error
+			err = errors.Join(err, sdb.Close())
```
Comment (hdonnay) [inline internal/rpm/find.go]:
```suggestion
			err := sdb.Close()
```

**Review by hdonnay — CHANGES_REQUESTED** [review]
Small simplification

File: internal/rpm/find.go (hunk 1 above)
Comment (crozzy) [reply internal/rpm/find.go]: :facepalm:

**Review by hdonnay — APPROVED** [review]
