### PR TITLE
java: check magic number

### LINKED ISSUE #434: failed to scan all layer contents: zip error: zip: not a valid zip file
I've seen this message in logs, and I'm not sure where it comes from.

Needs investigation.

### PR DESCRIPTION
**Pull request by hdonnay**
This change looks at the magic number if something appears to be a jar
based on the filename.

Closes #434

Signed-off-by: Hank Donnay <hdonnay@redhat.com>

### CODE REVIEW

**Comment by hdonnay** [comment]
does this need backports?

File: java/common.go [hunk 1]
```diff
@@ -34,3 +37,29 @@ Outer:
...
+	// (ending in "\x05\x06" and "\x07\x08" respectively) for zips, but if I
+	// find those in use I'm going to delete this entire package and go flame
+	// some people on IRC.
+	zipHeader = []byte{'P', 'K', 0x03, 0x04}
+)
+
+// PeekHeader looks at the magic prefix of the current file pointed at by the
+// tar.Reader and returns either the entirety of the file as an io.Reader or an
+// error.
+func peekHeader(tr *tar.Reader) (io.Reader, error) {
```
Comment (crozzy) [inline java/common.go:56]: What is the point of returning the file as well as the error? Is there another case you're thinking about or is it because we need the contents anyway so might as well return them?

**Review by crozzy — DISMISSED** [review]
LGTM, just one question

**Review by crozzy — DISMISSED** [review]

**Comment by hdonnay** [comment]
Merging via superpowers, because the commit hasn't changed.
